### ISSUE TITLE
Create / Update vulnerability categories in new or existing reports 

### ISSUE THREAD

**Issue by MCM-Mike** [My-Random-Thoughts/Rapid7Nexpose#20]
First of all, thank you for your work!

I do need some help solving a problem with categories.
Sometimes its needed to add or remove new categories to a lot of reports based on current needs. 

From https://help.rapid7.com/insightvm/en-us/api/index.html#operation/getReports 
>categories Object
The vulnerability categories to include or exclude in the report. Only included or excluded may be specified, not both.

This action to add or remove certain categories on existing or new reports would be helpful.
If you already did implement it, just point me please to the correct file(s).

**Comment by My-Random-Thoughts** [comment]
Hello and thanks for using my module.

There is currently no way of creating new reports or editing existing ones with my module, only run existing ones.
I have attempted to write the code for creating new reports several times, it's a very complicated beast due to the shear number of options available.

For your specific use-case, it may not be too difficult to implement yourself, it would require looking at https://help.rapid7.com/insightvm/en-us/api/index.html#operation/updateReport and passing in the id of the report and the new required categories filter. 

Sorry it's not the answer you wanted, but I hope it helps.

**Comment by MCM-Mike** [comment]
closing this as my issue was answered.
